* LS VERBOSE ALL OFF
* DV VERBOSE ALL OFF
* APP VERBOSE ALL OFF
* LS VERBOSE STATUS ON
* LS VERBOSE ERROR ON
* DV VERBOSE STATUS ON
* DV VERBOSE ERROR ON
* APP VERBOSE STATUS ON
* APP VERBOSE ERROR ON

* APP VERBOSE TRAFFIC ON
#* DV VERBOSE TRAFFIC ON
* DV VERBOSE DEBUG ON

TIME 60000
